// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASwQtUNqNkDhQPFai7fFuwTS-9AIc8b40',
    appId: '1:154777859669:web:521b92b96fccce611206dc',
    messagingSenderId: '154777859669',
    projectId: 'phisggurdelite',
    authDomain: 'phisggurdelite.firebaseapp.com',
    storageBucket: 'phisggurdelite.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrH2eyX1A1vfwhn_B1Q-D252ezkeqg7LY',
    appId: '1:154777859669:android:b76fbc6c8a4c49611206dc',
    messagingSenderId: '154777859669',
    projectId: 'phisggurdelite',
    storageBucket: 'phisggurdelite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQZivbRQLSSxUapsXv7IEB8Pjydvkiu4E',
    appId: '1:154777859669:ios:069047a1c1c8daf51206dc',
    messagingSenderId: '154777859669',
    projectId: 'phisggurdelite',
    storageBucket: 'phisggurdelite.firebasestorage.app',
    iosBundleId: 'com.example.phishguardLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQZivbRQLSSxUapsXv7IEB8Pjydvkiu4E',
    appId: '1:154777859669:ios:069047a1c1c8daf51206dc',
    messagingSenderId: '154777859669',
    projectId: 'phisggurdelite',
    storageBucket: 'phisggurdelite.firebasestorage.app',
    iosBundleId: 'com.example.phishguardLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASwQtUNqNkDhQPFai7fFuwTS-9AIc8b40',
    appId: '1:154777859669:web:e5fa1e954a521bcc1206dc',
    messagingSenderId: '154777859669',
    projectId: 'phisggurdelite',
    authDomain: 'phisggurdelite.firebaseapp.com',
    storageBucket: 'phisggurdelite.firebasestorage.app',
  );
}
